"""add user agent permissions

Revision ID: c6f3561b2a8d
Revises: f080022fe0ab
Create Date: 2026-07-13 15:28:56.483387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f3561b2a8d'
down_revision: Union[str, None] = 'f080022fe0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_agent_permissions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "agent",
            sa.Enum("crawler", "analysis", "lyrics", "music", name="agent_type"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "agent"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_agent_permissions")
    sa.Enum("crawler", "analysis", "lyrics", "music", name="agent_type").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
