"""add ranking analysis and lyrics workflows

Revision ID: d46f1588ed37
Revises: e7f2c52144a1
Create Date: 2026-07-13 18:59:06.803736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46f1588ed37'
down_revision: Union[str, None] = 'e7f2c52144a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranking_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('chart_code', sa.String(length=50), nullable=False),
    sa.Column('chart_name', sa.String(length=100), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source_updated_date', sa.Date(), nullable=True),
    sa.Column('item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'chart_code', 'snapshot_date', name='uq_ranking_snapshot_day')
    )
    op.create_index(op.f('ix_ranking_snapshots_platform'), 'ranking_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_snapshot_date'), 'ranking_snapshots', ['snapshot_date'], unique=False)
    op.create_table('analysis_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_tasks_status'), 'analysis_tasks', ['status'], unique=False)
    op.create_table('collection_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('chart_code', sa.String(length=50), nullable=False),
    sa.Column('chart_name', sa.String(length=100), nullable=False),
    sa.Column('source_mode', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ranking_snapshots.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_tasks_platform'), 'collection_tasks', ['platform'], unique=False)
    op.create_index(op.f('ix_collection_tasks_snapshot_date'), 'collection_tasks', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_collection_tasks_status'), 'collection_tasks', ['status'], unique=False)
    op.create_table('ranking_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('source_song_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('artist', sa.String(length=300), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ranking_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'rank', name='uq_ranking_entry_rank'),
    sa.UniqueConstraint('snapshot_id', 'source_song_id', name='uq_ranking_entry_song')
    )
    op.create_index(op.f('ix_ranking_entries_artist'), 'ranking_entries', ['artist'], unique=False)
    op.create_index(op.f('ix_ranking_entries_snapshot_id'), 'ranking_entries', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_title'), 'ranking_entries', ['title'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('trend_summary', sa.Text(), nullable=False),
    sa.Column('trend_metrics', sa.JSON(), nullable=False),
    sa.Column('creation_directions', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('provider_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('analysis_task_entries',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['ranking_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'entry_id')
    )
    op.create_table('lyrics_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('analysis_report_id', sa.Integer(), nullable=True),
    sa.Column('direction_index', sa.Integer(), nullable=True),
    sa.Column('title_hint', sa.String(length=200), nullable=True),
    sa.Column('theme', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=30), server_default='中文', nullable=False),
    sa.Column('genre_tags', sa.JSON(), nullable=False),
    sa.Column('mood_tags', sa.JSON(), nullable=False),
    sa.Column('scene_tags', sa.JSON(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('tempo', sa.String(length=30), nullable=True),
    sa.Column('vocal_gender', sa.String(length=30), nullable=True),
    sa.Column('vocal_style', sa.String(length=200), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_report_id'], ['analysis_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lyrics_tasks_status'), 'lyrics_tasks', ['status'], unique=False)
    op.create_table('lyrics_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('style_prompt', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['lyrics_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version_number', name='uq_lyrics_task_version')
    )
    op.create_index(op.f('ix_lyrics_versions_task_id'), 'lyrics_versions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lyrics_versions_task_id'), table_name='lyrics_versions')
    op.drop_table('lyrics_versions')
    op.drop_index(op.f('ix_lyrics_tasks_status'), table_name='lyrics_tasks')
    op.drop_table('lyrics_tasks')
    op.drop_table('analysis_task_entries')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_ranking_entries_title'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_snapshot_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_artist'), table_name='ranking_entries')
    op.drop_table('ranking_entries')
    op.drop_index(op.f('ix_collection_tasks_status'), table_name='collection_tasks')
    op.drop_index(op.f('ix_collection_tasks_snapshot_date'), table_name='collection_tasks')
    op.drop_index(op.f('ix_collection_tasks_platform'), table_name='collection_tasks')
    op.drop_table('collection_tasks')
    op.drop_index(op.f('ix_analysis_tasks_status'), table_name='analysis_tasks')
    op.drop_table('analysis_tasks')
    op.drop_index(op.f('ix_ranking_snapshots_snapshot_date'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_platform'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    # ### end Alembic commands ###
